@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(mediatorBoundary, "Módulo Mediador") {
    Component(mediator, "OrderMediator", "Component", "Orquestra o fluxo do pedido baseada em eventos.")
}

ContainerQueue(rabbitmq, "RabbitMQ")

' Fluxo de Sucesso
Rel(rabbitmq, mediator, "Lê OrderCreatedEvent", "q.order-created")
Rel(mediator, rabbitmq, "Envia ReserveStockCommand", "ex.order -> stock.reserve")

' Fluxo de Falha
Rel(rabbitmq, mediator, "Lê StockReservationFailedEvent", "q.stock-failed")
Rel(mediator, rabbitmq, "Envia CancelOrderCommand", "ex.order -> order.cancel")

@enduml